apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:juf9iLGpgDr5w2JLT0nz01V3Ap+E37BNItHqXdb28Ou31076NzXWrC3zgs4q4Pa9vFEDBCMg9biUgqFI1/mTPdY=,iv:N5DcOWck5F9gd/M/2l4Jrhpbk3CbemmJhXze+A5pvwA=,tag:T9IuUGGXJ+9ib2RkOMd1Iw==,type:comment]
    #ENC[AES256_GCM,data:GMYAgb5wd2SXyIySK7+n53PFiRMYIqa4Y/xZn8M771Y7WnInr0zsYa4uqiM=,iv:WQehPRBzCiEcflyuhwhEtP/DUUlwgF2F7XPyj0dAwwg=,tag:S7npO/XjOZAx2Z877kBpsw==,type:comment]
    VIP: ENC[AES256_GCM,data:XYmMELW5g5Ukd0ae/Ag=,iv:70d5ZaV1PSULDwj2TAZSciYf7YgctQl1rejF8sHajm0=,tag:9r/9GLTyTWmclUAvdscnXQ==,type:str]
    #ENC[AES256_GCM,data:+jAutnC80bgYIo4ttXtp2OgXnFK2uYC/ZbY=,iv:dTQ4b4nt6Lj9/By7LyUTAHcLtZB52EPqqlWWk+CZjho=,tag:LSUHJAORSGLYT94asfLDEQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:3M1ur88AB4Ojqz4reLQ=,iv:uSv26upaAhRHRoO7PGsdBCfXLBX4RP/ByEclIAM9Us4=,tag:1DyP9STTRYiF7ce+fqUN2g==,type:str]
    #ENC[AES256_GCM,data:9ljJseevoHD3o2/fWfhrW5ivPtX/N+ltzYo/+vVSDZeMTA==,iv:SKwvUOTfui4FlmYkH7p4sA5rs7NCkRMAeBHyErKzYs0=,tag:NrCDAwYOJWEoWPdHqVYJ2A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:5R1QjXjyk7akP+Ov,iv:zewwWIDMw6biXm8vYgcpg6TCYDk4ofIAXxYeh4aWkh4=,tag:6rAf6bAojLXhucWh0MSBNw==,type:str]
    #ENC[AES256_GCM,data:5hwYbsewfmKpI4fqlg88C2O23KMrxhqx3Aqbn3MNy0MI6WfzexsdfMaAIIaRI14=,iv:/H5k5XljIjVPVUg10xz8qPPp/V5ogWb2LjwwIUl+zng=,tag:rVGWPvbhrZ/tR+qPYTCSeA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:rsBgI87AK8zZwCpgxeK3kqm+72ai0xrgaG4jOMg=,iv:KN1O6ts8DJUJhZbfCQ7xIdYJksGBfQP+xCQvMOUKedI=,tag:5rZrW+JshjCwAGcd8P35aQ==,type:str]
    #ENC[AES256_GCM,data:XJjmGKfsFfDKwfodC3laXYICmK6Cv5NZ1JGLQUt45vZUiNHByMAB7rZxfSiR/uzMU6P/hsNwsmyc/xj+xWyQHLNyZGd3XpnC4nWEwlJGRbU=,iv:0aI48kybiAzZLQi5zr3plc1jEEDO3s/TQmICpo3EVkc=,tag:WgZw3cQVBa0r67yHH4wp5A==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:2dTihIEv8LTUv0mnqeg=,iv:nfNSM0Bp4xrAsIxh20bwZElHV4Mu4bQeSab2u3/OMOI=,tag:RgpCm7Lo3bhDzDm6yA+jzA==,type:str]
    #ENC[AES256_GCM,data:QcvBWe6ffWxSPWTJJkOGfp8A7mfH36zsl6L6j2ANSFL9lTw0TlWmj6doBV+Tg9UbJaMnjTPytoGFiV8h1jD3RZsqosk=,iv:buk3kWwVTLaIBKLMtExUMkTPhN2gGvI1xFzmAouNSKw=,tag:VXziIFH0x9oeDA7SC1OswQ==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:yXOaMF12TIcEEc01b9Q=,iv:JzI54vTZ8wslqyN1jJYV9kFLBy91ZwGAwFaeGFRHu1c=,tag:X7UhkXlEbDoPVA8Nlzm2tA==,type:str]
    #ENC[AES256_GCM,data:guTYJ1Bf5Uk2Lp25iYf2xi0T3B4xSjirEgslyE6sxMFaCtp2NnhgNT2BZFaTSsUOyt+VwaTt2JA=,iv:x86h8uqgpINkeH2NEvrTDpoIZLoZIScHiXEj43GgUsU=,tag:13MTS2tIXOuu/hb42jRAQg==,type:comment]
    #ENC[AES256_GCM,data:k0XGO2fXqniduMQuutr5T/xGxQfnRF6O5A==,iv:YPNGXD24f/BqY1knYNUinOAJgFhUYxD4QLKVyQjFylw=,tag:dLJnaPRmZY5ySdvml0nv9Q==,type:comment]
    GITHUB_REPOSITORY: ""
    #ENC[AES256_GCM,data:ULMaAqmjja24xdkqBQ==,iv:OeosiCuI8fZp8CI0+t8aKoQzPlUEUrP2v780ZbzLv+M=,tag:BKBtYzJXIqS8sVbzTg5haA==,type:comment]
    PODNET: ENC[AES256_GCM,data:jyj5AEXpxV48ASZ6rw==,iv:WCIUxK9cZ366Zw0iYp9ekIt+K++c8Yg1x0r/7nN946w=,tag:FtRcKsO8AOAesX812GzGdw==,type:str]
    SVCNET: ENC[AES256_GCM,data:fzDfjOUtIiFeidejeg==,iv:ffX1A2dFQWMFzI2shAYtBb4zqVUmIYMJ3vWe16LOJuo=,tag:iLl86d2hxptpfrmg1bVKgQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x0pq9ley6egs8g0mdhrgmg5qq2pq0ra8vkqcq8kqfmcpn4haf4tqukmslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRkpBOVlLTjlCK0NvRDFO
            OFZjWXMxVlFPMDVzalMxbklZQ2IrUHg5SUE4CkZPQUxRWnMxKzJDSmZQZWZrOHFD
            UG5VU3NPL21neGQvZHc5R29qQnRqQTgKLS0tIHdEbmZpUWFZRkV2OEVDSGd0cG5k
            SDlOYWJ0WlgyU2dnTWZ3aUhsYkNsaGcK7iOxbcYoilHDv9yoYXcl2EsC6RV4QaDD
            546b15ReZi0l8vjccpx6t1SStvSS0y98+zM7b4XivmiA7gdV5wpvOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-03T17:33:21Z"
    mac: ENC[AES256_GCM,data:NCy7jBLWTgO5nTyEm64BGNA5UVz2fqFR96bt0H5ON7cQxuRfeoEkMzDc/dRYwZ5lOQLK5mmXpEbFrF+4ibyGEkabbxhK0kBnVxacGwh4kOIOUkBjeoTRY5AX43BbFcWPI3oRH75NvoKljBA9ZPM+J69eXIvSldhaDycyc76DPSs=,iv:gEUATw+MeYqpvEH0Xk4jsEx+aihVgFhyGD8IR15AJsI=,tag:PcziXNFnBvlpbXU22LC9yA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
