apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:2nqvY4fk/fESsp2HBXfhi15DS6fHaJ1tkUMx1JxKro0rR5txWV+wP5LbcrEKhJGBbxAF9eh4YLSEYrcZKKWq3aM=,iv:f+GWPwIVDNP1mWn5wr7O+hZjE0MPdMGmi4cUksVQ8GE=,tag:DWkK6NP4aBJfO1WlpqibhQ==,type:comment]
    #ENC[AES256_GCM,data:VFF9HrYAYJz8/nbmfr8bOAjlbivYfMmpbzrLLFihAMjeZJWS0xiMuggoSSo=,iv:6KslOWiZ6pCh4U4Q7tQKmqxmAiT5VUZSLPZIJzmTOXk=,tag:wELFVF5XvKOqL2zi0jc5CQ==,type:comment]
    VIP: ENC[AES256_GCM,data:fdWDs+DYWSY3ccKHDkA=,iv:Ck8JRBUEsnM68/Ao42aRg7l7WHdNySYpNrTXgyqEDrU=,tag:lSx9SktLJ4h4j6UNriwbLQ==,type:str]
    #ENC[AES256_GCM,data:9vIPdwSeLv4agI8//OGq7DtQG8DSdw9WMWQ=,iv:XD/Mas7CkN7OtcIcBROlMJLnQBqjca8DXP2/zclXFOU=,tag:07R6C6iOqWd+R/bKkLB7TA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:qEsUhGTqq1xPukJACis=,iv:bLDhWoLqZdCGYpI7i8d2B2M1iUYd09Yo3sIdmRrDT50=,tag:9ddnQKTkuyZgWNw9Jv2vfg==,type:str]
    #ENC[AES256_GCM,data:sDvoJzpnBZ0jz7YcgdZiMmR+WQUdDqDkdbBX+1Ndze2hOQ==,iv:vfRB9RDRMvRjlK6aaHQ65SV/cXjXtb0uPnET0s6+IAU=,tag:MisdLdAzIAtFC8l0DcjvNQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:EiV9S0N4q3we9o+i,iv:eIC6wUgNCcPEnBFLRLPB33wFIAPDxZMdiDU8sidIxpM=,tag:MJ0gaFdMyTARArKMRKvnFg==,type:str]
    #ENC[AES256_GCM,data:+hzFbcwI2G0Y6lrODF/uH5GdMcOw9L1BhzpDgVu4Pu1y1h929RuB9yJN2Qim7+g=,iv:MZ/lIpH+nakj9M3INiFFfXU8BMAjHnRsw5Okbb5/3Ac=,tag:M62MD7pUk8j6jebx1M/8mA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:/unHaW1XLQzWpq+n390g95QZui9HxLy80p9vjZc=,iv:tICo3R7NfaFlURmugAwYQegteXrM2CPqVyHhdfhmK5E=,tag:xtNljRV03X2O/PkFcVKj3g==,type:str]
    #ENC[AES256_GCM,data:4nSBcgMtJzG8bUFQdXMA4ezVnKWPfdLMkmm+Kg0ZyyTT8uax7843l2+LfMxeLAAyPl/j0PZUy696fpJiE5rmy4RzUZ2pc1L855kgKJBiukM=,iv:xElQOPibLGQGlvzGZzcouLf+GVgTTxgaaUWAQAzfki0=,tag:xkuOX33ZUBxmPiylTPd1Tw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:tjXcOF17C6B8um8hsHs=,iv:WCTaC8/hjPZTesrxIKiifHVZhd5yxA7QpmLKINkeUe8=,tag:PY5SS9Ej1JxRvUR4YUxL/g==,type:str]
    #ENC[AES256_GCM,data:4XkCDlPp+wUzm46rh9wB6YNmfZbzbg1VTDTr6AFXnUuP3iVXsLqsbfpCCS6ttGlBljvHYA2nLpX4/q0wWmnnb4U9M7Q=,iv:r2md/e9jFgqiizWONakO8reVGIud1PovJxJOqPIHt+E=,tag:2Y1gFoOuW/LdJmEBmDdnwA==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:Np+ytz6+CB/6dBKkFRk=,iv:yYdZjr/7TqfqWVlU7KEBThE2/qatEc6Q1Gb2F9s2vzM=,tag:cntCqXigysqrCQFBe23RUA==,type:str]
    #ENC[AES256_GCM,data:Q0BroRyrgKkAgFEx9W1Zx9boieOzEj3eX70xjM1d0u662f8amlbWnoPujIa1GGoOcNcjbbyPuCs=,iv:IyBpua1TsbqSEyXcdjdTVrxEyyxy/V/X8ms9eOJs25Y=,tag:YglQmxYzy97+Vp6kJxXsoQ==,type:comment]
    #ENC[AES256_GCM,data:P6Xa61gEks0WEAM77FwZHHbElMiOQ3Tybw==,iv:LL7XJ+jFgJ0Xb5htBLv71OI87unA31ZRQ3ed5ooo9KA=,tag:Ga0NH17Im2rnC//eAz9VGA==,type:comment]
    GITHUB_REPOSITORY: ""
    #ENC[AES256_GCM,data:xaCAK+5Oald4fl/XJQ==,iv:M2eiOf0l+/W+j4P+6i56lWHSJ4WYlCGxUQw0Dj2nFns=,tag:Z191/9Pwj4TEHGax/oDDBA==,type:comment]
    PODNET: ENC[AES256_GCM,data:TaZue0kvtt0rQ6g8Vw==,iv:+7WAz7Qs+yPblyNwHDB1Xkj7Gc+ftoGmPEOS97RP6Ww=,tag:pGMFvU+Sj9YQcTWRCj9cGQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:8yj/zUXnJP3c2tcHUw==,iv:hUrHafVxkpXh1jKN3NTCLNWa80KNXg+Z5FdybYA2NaY=,tag:FmHVori8G/8gn/VzR/adVA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x0pq9ley6egs8g0mdhrgmg5qq2pq0ra8vkqcq8kqfmcpn4haf4tqukmslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaDRvRUFZbWI0USs4bUVM
            S2FITGZ0bmQvNVlteDU5ek1IdnFNK0F2eDJnCkVsTFNXOU9EYjhCbHpsVUFtR1JV
            TVRVazZxdHJ3MzZPZUdxWUVjL2VhMGMKLS0tIHdiNzlpL0UzdFlEMk41YjlpbE5Z
            TEtuYnhVVWtORFFVY0ZwWFNYYUdsVzgKf53U0XRKdWwwS/PHzzkRRxUBDhJKFtyg
            9ChDdvqeVxTAM2SxhjLybif1j7/couf6JePkBHo58U/i4EH0vlmRow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-02T19:02:50Z"
    mac: ENC[AES256_GCM,data:N3oLNEgANVkehd3RoqR6+4xNpS/9TzasZ1LOsmj/rB0xkeWMMuQo2rpz3VuMM1R6JdNY+8tFsHZemnA7kkIrgrFtGgULuAFsNMS5GS9vauoPZAEtT0LV3pWly1Gm26VTXgzlR+t46WOe4ZQpeRfD4XWz8qmgHBPwvHd99J/FW0w=,iv:pqIA8YHWIrVpijBp/jd7iHy7ZwVX5MIcq5kD5HLgd3k=,tag:m6ketrfNXJO0hS3p/pdGoA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
